<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Tomas-PC" name="tomas_niro.training.globant.com.tests.Tests" tests="9" failures="0" timestamp="25 Mar 2015 02:36:35 GMT" time="829.755" errors="1">
  <testcase name="case7" time="149.846" classname="tomas_niro.training.globant.com.tests.Tests"/>
  <testcase name="case3" time="47.606" classname="tomas_niro.training.globant.com.tests.Tests"/>
  <testcase name="case1" time="25.339" classname="tomas_niro.training.globant.com.tests.Tests"/>
  <testcase name="case9" time="209.398" classname="tomas_niro.training.globant.com.tests.Tests"/>
  <testcase name="case8" time="147.923" classname="tomas_niro.training.globant.com.tests.Tests"/>
  <testcase name="case5" time="158.121" classname="tomas_niro.training.globant.com.tests.Tests"/>
  <testcase name="case6" time="25.141" classname="tomas_niro.training.globant.com.tests.Tests">
    <error type="java.lang.AssertionError" message="expected [That date/time has already passed. Please select a new date/time.] but found []">
      <![CDATA[java.lang.AssertionError: expected [That date/time has already passed. Please select a new date/time.] but found []
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at tomas_niro.training.globant.com.tests.Tests.case6(Tests.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- case6 -->
  <testcase name="case4" time="41.793" classname="tomas_niro.training.globant.com.tests.Tests"/>
  <testcase name="case2" time="24.588" classname="tomas_niro.training.globant.com.tests.Tests"/>
</testsuite> <!-- tomas_niro.training.globant.com.tests.Tests -->
